### ISSUE TITLE
Update KeepAliveD cookbook to reflect new options for keepalived.conf

### ISSUE THREAD

**Issue by predatorian3** [chef-cookbooks/keepalived#49]
### Cookbook version
https://supermarket.chef.io/cookbooks/keepalived/versions/3.0.1

### Chef-client version
Chef-Client 12.18.31 RHEL 6.8 x86_64

### Platform Details
Red Hat Enterprise Linux 6.8 x86_64

### Scenario:
Attempting to use new settings in KeepAliveD Configuration to allow scripts to be executed with KeepAliveD 1.3.2. KeepAliveD 1.2.13, the one in most Yum Repositories, has issues with SELinux allowing it to execute scripts. After building from source for 1.3.2, scripts are attempting to be executed, but there are no spots for settings listed here. 
https://github.com/acassen/keepalived/blob/master/doc/keepalived.conf.SYNOPSIS

### Steps to Reproduce:
Build KeepAliveD 1.3.2 from source. Attempt to input `user` into `vrrp_script`, chef-client run fails. 

### Expected Result:
This should add the user to the `vrrp_script` block allowing KeepAliveD to execute vrrp_scripts, as well as notifiy scripts. 

### Actual Result:
```root@serverzbxsvr00:/opt/cookbooks
16:52:39 # chef-client -z -o recipe[zabbix_keepalived::default]
[2017-02-07T16:52:49+00:00] WARN: No config file found or specified on command line, using command line options.
Starting Chef Client, version 12.18.31
[2017-02-07T16:52:53+00:00] WARN: Run List override has been provided.
[2017-02-07T16:52:53+00:00] WARN: Original Run List: []
[2017-02-07T16:52:53+00:00] WARN: Overridden Run List: [recipe[zabbix_keepalived::default]]
resolving cookbooks for run list: ["zabbix_keepalived::default"]
Synchronizing Cookbooks:
  - keepalived (3.0.1)
  - zabbix_keepalived (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /root/.chef/local-mode-cache/cache/cookbooks/zabbix_keepalived/recipes/default.rb
================================================================================

NoMethodError
-------------
undefined method `user' for ChefKeepalived::Resource::VrrpScript

Cookbook Trace:
---------------
  /root/.chef/local-mode-cache/cache/cookbooks/zabbix_keepalived/recipes/default.rb:24:in `block in from_file'
  /root/.chef/local-mode-cache/cache/cookbooks/zabbix_keepalived/recipes/default.rb:18:in `from_file'

Relevant File Content:
----------------------
/root/.chef/local-mode-cache/cache/cookbooks/zabbix_keepalived/recipes/default.rb:

 17:
 18:  keepalived_vrrp_script 'chk_zabbix' do
 19:    interval 2
 20:    weight 20
 21:    fall 3
 22:    rise 1
 23:    script '/etc/keepalived/notify.sh chk'
 24>>   user 'root' 'root'
 25:    init_fail
 26:  end
 27:
 28:  keepalived_vrrp_instance 'ccf_1' do
 29:    notify_master '"/etc/keepalived/notify.sh start" root root'
 30:    notify_backup '"/etc/keepalived/notify.sh stop" root root'
 31:    notify_fault '"/etc/keepalived/notify.sh stop" root root'
 32:    smtp_alert true
 33:    state 'MASTER'

Platform:
---------
x86_64-linux


Running handlers:
[2017-02-07T16:52:53+00:00] ERROR: Running exception handlers
Running handlers complete
[2017-02-07T16:52:53+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 03 seconds
[2017-02-07T16:52:53+00:00] FATAL: Stacktrace dumped to /root/.chef/local-mode-cache/cache/chef-stacktrace.out
[2017-02-07T16:52:53+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-02-07T16:52:53+00:00] ERROR: undefined method `user' for ChefKeepalived::Resource::VrrpScript
[2017-02-07T16:52:53+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)```

**Comment by nathwill** [comment]
thanks for the heads up!
