### ISSUE TITLE
ArgumentError when setting keepalived_vrrp_instance state property

### ISSUE THREAD

**Issue by nickpendleton** [chef-cookbooks/keepalived#55]
### Cookbook version
3.1.0

### Chef-client version
12.19.36

### Platform Details
CentOS 7

### Scenario:
keepalived_vrrp_instance throws and ArgumentError when setting the state parameter. "wrong number of arguments (given 1, expected 0)"

### Steps to Reproduce:
Here's the resource block I'm getting this on:
```
keepalived_vrrp_instance 'VI_1' do
      virtual_router_id routerId
      state nodeState
      interface "eth0"
      priority routerPriority
      unicast_src_ip source_ip
      unicast_peer peer_ip
      virtual_ipaddress vip
      track_script chk_haproxy
  end
```

The same error appears for this property order as well: 
```
keepalived_vrrp_instance 'VI_1' do
      state nodeState
      virtual_router_id routerId
      interface "eth0"
      priority routerPriority
      unicast_src_ip source_ip
      unicast_peer peer_ip
      virtual_ipaddress vip
      track_script chk_haproxy
  end
```

Both error when setting the state.

### Expected Result:
State is set in keepalived configuration and VRRP instance works properly

### Actual Result:
Chef client fails to run. 

```
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/ps-keepalived/recipes/default.rb
================================================================================

ArgumentError
-------------
wrong number of arguments (given 1, expected 0)

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/ps-keepalived/recipes/default.rb:64:in `block in from_file'
  /var/chef/cache/cookbooks/ps-keepalived/recipes/default.rb:62:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/ps-keepalived/recipes/default.rb:

 57:        interval 2
 58:        weight 2
 59:        script '"killall -0 haproxy"'
 60:    end
 61:
 62:    keepalived_vrrp_instance 'VI_1' do
 63:        virtual_router_id routerId
 64>>       state nodeState
 65:        interface "eth0"
 66:        priority routerPriority
 67:        unicast_src_ip source_ip
 68:        unicast_peer peer_ip
 69:        virtual_ipaddress vip
 70:        track_script chk_haproxy
 71:    end
 72:
 73:  else

Platform:
---------
x86_64-linux
```

I have tried `state 'MASTER'` as well, just as you have in the README. That also doesn't work.

**Comment by tas50** [comment]
The state properly actually collides with a built in chef state method which is the one you're seeing now. In the 3.1 cookbook release we renamed state to master. If you update your resource to use master instead of state that should go away and you'll be ready for Chef 13

**Comment by nickpendleton** [comment]
K, well that fixed that problem. Now, a new problem. I can open a new issue if you would like, but I'll explain it here for now.

chef-client continues past the vrrp resource blocks. It looks like it continues to the next recipes in the run list, but eventually, this happens:

```
Recipe: ps-keepalived::default
  * keepalived_vrrp_script[chk_haproxy] action create[2017-03-21T16:25:53-07:00] INFO: Processing keepalived_vrrp_script[chk_haproxy] action create (ps-keepalived::default line 55)
 (up to date)
  * keepalived_vrrp_instance[VI_1] action create[2017-03-21T16:25:53-07:00] INFO: Processing keepalived_vrrp_instance[VI_1] action create (ps-keepalived::default line 61)
[2017-03-21T16:25:53-07:00] INFO: Running queued delayed notifications before re-raising exception


  Running handlers:
[2017-03-21T16:25:53-07:00] ERROR: Running exception handlers
  Running handlers complete
[2017-03-21T16:25:53-07:00] ERROR: Exception handlers complete
  Chef Client failed. 0 resources updated in 24 seconds
[2017-03-21T16:25:53-07:00] INFO: Sending resource update report (run-id: 6d02029d-f562-420c-86cb-854c61bb014c)
[2017-03-21T16:25:53-07:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2017-03-21T16:25:53-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-03-21T16:25:53-07:00] ERROR: authentication is required
[2017-03-21T16:25:54-07:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

No error text in here. Here's the corresponding stacktrace:

```
Generated at 2017-03-21 16:25:53 -0700
Chef::Exceptions::ValidationFailed: authentication is required
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/property.rb:382:in `get'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/property.rb:276:in `call'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/property.rb:533:in `authentication'
/var/chef/cache/cookbooks/keepalived/libraries/helpers.rb:24:in `block in conf_string'
/var/chef/cache/cookbooks/keepalived/libraries/helpers.rb:23:in `each_pair'
/var/chef/cache/cookbooks/keepalived/libraries/helpers.rb:23:in `conf_string'
/var/chef/cache/cookbooks/keepalived/libraries/resources.rb:165:in `to_conf'
/var/chef/cache/cookbooks/keepalived/libraries/resources.rb:37:in `block in <class:Config>'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/property.rb:671:in `instance_exec'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/property.rb:671:in `exec_in_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/property.rb:689:in `stored_value_to_output'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/property.rb:370:in `get'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource.rb:675:in `block in to_text'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource.rb:674:in `map'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource.rb:674:in `to_text'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/formatters/error_inspectors/resource_failure_inspector.rb:46:in `add_explanation'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/formatters/error_mapper.rb:72:in `resource_failed'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/formatters/base.rb:139:in `resource_failed'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/formatters/doc.rb:313:in `resource_failed'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/event_dispatch/dispatcher.rb:43:in `call'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/event_dispatch/dispatcher.rb:43:in `block in call_subscribers'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/event_dispatch/dispatcher.rb:34:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/event_dispatch/dispatcher.rb:34:in `call_subscribers'
(eval):2:in `resource_failed'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource.rb:634:in `rescue in run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource.rb:620:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:670:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:665:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:665:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:704:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:284:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:295:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:283:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:283:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:248:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:236:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/bin/chef-client:26:in `<top (required)>'
/bin/chef-client:57:in `load'
/bin/chef-client:57:in `<main>'

>>>> Caused by Chef::Exceptions::ValidationFailed: authentication is required
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/property.rb:382:in `get'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/property.rb:276:in `call'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/property.rb:533:in `authentication'
/var/chef/cache/cookbooks/keepalived/libraries/helpers.rb:24:in `block in conf_string'
/var/chef/cache/cookbooks/keepalived/libraries/helpers.rb:23:in `each_pair'
/var/chef/cache/cookbooks/keepalived/libraries/helpers.rb:23:in `conf_string'
/var/chef/cache/cookbooks/keepalived/libraries/resources.rb:165:in `to_conf'
/var/chef/cache/cookbooks/keepalived/libraries/resources.rb:37:in `block in <class:Config>'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/property.rb:671:in `instance_exec'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/property.rb:671:in `exec_in_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/property.rb:689:in `stored_value_to_output'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/property.rb:370:in `get'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/property.rb:276:in `call'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/property.rb:533:in `content'
/var/chef/cache/cookbooks/keepalived/libraries/provider.rb:60:in `block in manage_config_file'
/var/chef/cache/cookbooks/keepalived/libraries/provider.rb:59:in `tap'
/var/chef/cache/cookbooks/keepalived/libraries/provider.rb:59:in `manage_config_file'
/var/chef/cache/cookbooks/keepalived/libraries/provider.rb:46:in `block in action_create'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/provider.rb:176:in `converge_by'
/var/chef/cache/cookbooks/keepalived/libraries/provider.rb:45:in `action_create'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource.rb:622:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/2.3.0/forwardable.rb:189:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:670:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:665:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:665:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:704:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:284:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:295:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:283:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:283:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:248:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:236:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/bin/chef-client:26:in `<top (required)>'
/bin/chef-client:57:in `load'
/bin/chef-client:57:in `<main>'
```

Also, I did correct my resource block. Here it is now:

```
keepalived_vrrp_instance 'VI_1' do
      master isMaster
      virtual_router_id routerId
      interface "eth0"
      priority routerPriority
      unicast_src_ip source_ip
      unicast_peer [peer_ip]
      virtual_ipaddress [vip]
      track_script ['chk_haproxy']
end
```

And finally, here's the values of the variables above:

```
ismaster = true
routerId = 54
routerPriority = 255
source_ip = "192.168.0.137"
peer_ip = "192.168.0.138"
vip = "192.168.0.139"
```

I do apologize if this is another problem caused by user error. This one just doesn't give me much to work with.

**Comment by nathwill** [comment]
you're missing the required `authentication` property, which takes a hash containing the keys `:auth_type` and `:auth_pass`, with `:auth_type` being one of "PASS" or "AH".

the relevant bit of the stacktrace is `Chef::Exceptions::ValidationFailed: authentication is required`. [see this bit](https://github.com/chef-cookbooks/keepalived/blob/e420c434496f39fdaf8328c95e22d9078bdee034/libraries/keepalived.rb#L125-L136)
