### ISSUE TITLE
keepalived::default does not converge on the latest CentOS 7 and Debian 9

### ISSUE THREAD

**Issue by bodgix** [chef-cookbooks/keepalived#62]
### Cookbook version
3.1.0

### Chef-client version
13.6.4-1

### Platform Details
centos-7
debian-9

### Scenario:
keepalived::default does not converge on the latest versions of debian-9 and centos-7

### Steps to Reproduce:
kitchen test centos-7
kitchen test debian-9

### Expected Result:
```
Finished in 0.22866 seconds (files took 0.29889 seconds to load)
26 examples, 0 failures
```

### Actual Result:
```
        * service[keepalived] action start

           ================================================================================
           Error executing action `start` on resource 'service[keepalived]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of /bin/systemctl --system start keepalived ----
           STDOUT:
           STDERR: Job for keepalived.service failed because the control process exited with error code. See "systemctl status keepalived.service" and "journalctl -xe" for details.
           ---- End output of /bin/systemctl --system start keepalived ----
           Ran /bin/systemctl --system start keepalived returned 1

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/keepalived/recipes/service.rb

            20: service 'keepalived' do
            21:   supports restart: true
            22:   action [:enable, :start]
            23:   subscribes :restart, 'file[keepalived.conf]', :delayed
            24:   subscribes :restart, 'file[keepalived-options]', :delayed
            25: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/keepalived/recipes/service.rb:20:in `from_file'

           service("keepalived") do
             action [:enable, :start]
             updated true
             default_guard_interpreter :default
             service_name "keepalived"
             enabled true
             running false
             masked false
             pattern "keepalived"
             declared_type :service
             cookbook_name "keepalived"
             recipe_name "service"
             supports {:restart=>true}
           end

           System Info:
           ------------
           chef_version=13.6.4
           platform=centos
           platform_version=7.4.1708
           ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
           program_name=chef-client worker: ppid=2723;start=16:30:01;
           executable=/opt/chef/bin/chef-client

         * service[keepalived] action restart

           ================================================================================
           Error executing action `restart` on resource 'service[keepalived]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of /bin/systemctl --system restart keepalived ----
           STDOUT:
           STDERR: Job for keepalived.service failed because the control process exited with error code. See "systemctl status keepalived.service" and "journalctl -xe" for details.
           ---- End output of /bin/systemctl --system restart keepalived ----
           Ran /bin/systemctl --system restart keepalived returned 1

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/keepalived/recipes/service.rb

            20: service 'keepalived' do
            21:   supports restart: true
            22:   action [:enable, :start]
            23:   subscribes :restart, 'file[keepalived.conf]', :delayed
            24:   subscribes :restart, 'file[keepalived-options]', :delayed
            25: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/keepalived/recipes/service.rb:20:in `from_file'

           service("keepalived") do
             action [:enable, :start]
             updated true
             default_guard_interpreter :default
             service_name "keepalived"
             enabled true
             running false
             masked false
             pattern "keepalived"
             declared_type :service
             cookbook_name "keepalived"
             recipe_name "service"
             supports {:restart=>true}
           end

           System Info:
           ------------
           chef_version=13.6.4
           platform=centos
           platform_version=7.4.1708
           ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
           program_name=chef-client worker: ppid=2723;start=16:30:01;
           executable=/opt/chef/bin/chef-client
```

**Comment by bodgix** [comment]
systemd journal reveals what the problem is:

```
Jan 09 16:34:34 default-centos-7 Keepalived[3398]: Starting Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2
Jan 09 16:34:34 default-centos-7 Keepalived[3398]: Unable to resolve default script username 'keepalived_script' - ignoring
Jan 09 16:34:34 default-centos-7 Keepalived[3398]: Opening file '/etc/keepalived/keepalived.conf'.
Jan 09 16:34:34 default-centos-7 Keepalived[3398]: Unable to find config file(s) '/etc/keepalived/conf.d/*.conf'.
Jan 09 16:34:34 default-centos-7 systemd[1]: keepalived.service: control process exited, code=exited status=3
Jan 09 16:34:34 default-centos-7 systemd[1]: Failed to start LVS and VRRP High Availability Monitor.
-- Subject: Unit keepalived.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit keepalived.service has failed.
--
-- The result is failed.
```

I created an empty file: */etc/keepalived/conf.d/empty.conf* and after that keepalived started succesfully:

```
[root@default-centos-7 ~]# touch /etc/keepalived/conf.d/empty.conf
[root@default-centos-7 ~]# systemctl start keepalived.service
[root@default-centos-7 ~]# systemctl status keepalived.service
● keepalived.service - LVS and VRRP High Availability Monitor
   Loaded: loaded (/usr/lib/systemd/system/keepalived.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2018-01-09 16:37:14 UTC; 13s ago
  Process: 3456 ExecStart=/usr/sbin/keepalived $KEEPALIVED_OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 3457 (keepalived)
   CGroup: /system.slice/keepalived.service
           ├─3457 /usr/sbin/keepalived -D
           ├─3458 /usr/sbin/keepalived -D
           └─3459 /usr/sbin/keepalived -D

Jan 09 16:37:14 default-centos-7 systemd[1]: Started LVS and VRRP High Availability Monitor.
Jan 09 16:37:14 default-centos-7 Keepalived_healthcheckers[3458]: Initializing ipvs
Jan 09 16:37:14 default-centos-7 Keepalived_vrrp[3459]: Registering Kernel netlink reflector
Jan 09 16:37:14 default-centos-7 Keepalived_vrrp[3459]: Registering Kernel netlink command channel
Jan 09 16:37:14 default-centos-7 Keepalived_vrrp[3459]: Registering gratuitous ARP shared channel
Jan 09 16:37:14 default-centos-7 Keepalived_vrrp[3459]: Opening file '/etc/keepalived/keepalived.conf'.
Jan 09 16:37:14 default-centos-7 Keepalived_vrrp[3459]: Opening file '/etc/keepalived/conf.d/empty.conf'.
Jan 09 16:37:14 default-centos-7 Keepalived_vrrp[3459]: Using LinkWatch kernel netlink reflector...
Jan 09 16:37:14 default-centos-7 Keepalived_healthcheckers[3458]: Opening file '/etc/keepalived/keepalived.conf'.
Jan 09 16:37:14 default-centos-7 Keepalived_healthcheckers[3458]: Opening file '/etc/keepalived/conf.d/empty.conf'.
```
